markdown: kramdown
nav:
  mission:
    label: 'Mission'
    path: '/mission/'
  impact:
    label: 'Impact'
    path: '/impact/'
  schools:
    label: 'Schools'
    path: '/schools/'
  team:
    label: 'Team'
    path: '/team/'
  jobs:
    label: 'Join'
    path: '/jobs/'
gems: ['kramdown']
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']

defaults:
  -
    scope:
      path: "homepage-videos"
    values:
      layout: "homepage-video"
  -
    scope:
      path: "team"
    values:
      title: "Team"
      header_text: "Weâ€˜re a team that believes<br>anything is possible."
